[package]
name = "entman"
version = "0.1.5"
authors = ["haslersn <sebastian.hasler@gmx.net>", "rojost <romanjost@fius.de"]
edition = "2024"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.11"
ldap3 = "0.11"
log = "0.4"
reqwest = "0.12"
rocket = { version = "0.5", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.9"
tokio = { version = "1.46" }

